name: FANotifier
description: Unofficial FA App.

publish_to: "none"

version: 1.1.1+7

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter


  flutter_inappwebview: ^6.1.5

  cupertino_icons: ^1.0.2
  webview_flutter: ^4.10.0

  visibility_detector: ^0.3.3

  http: ^1.3.0
  html: ^0.15.0

  #cached_network_image: ^3.4.1

  cached_network_image:
    git:
      url: https://github.com/LOCKEDFILE/flutter_cached_network_image.git
      ref: 0b3e640
      path: cached_network_image





  flutter_cache_manager: ^3.4.1
  flutter_staggered_grid_view: ^0.7.0
  shimmer: ^2.0.0

  url_launcher: ^6.0.20
  shared_preferences: ^2.1.1
  flutter_secure_storage: ^8.0.0
  provider: ^6.0.5
  like_button: ^2.0.2
  carousel_slider: ^5.0.0
  permission_handler: ^11.3.1
  path_provider: ^2.0.0
  fluttertoast: ^8.1.1
  dio_cookie_manager: ^2.1.1
  dio: ^5.1.2
  cookie_jar: ^3.0.1
  collection: ^1.17.0
  image_picker: ^0.8.4+3


  badges: ^2.0.3
  flutter_linkify: ^6.0.0
  extended_text: ^14.2.2

  flutter_switch: ^0.3.2


  flutter_local_notifications: ^18.0.1
  workmanager: ^0.5.2
  flutter_app_badge_control: ^0.0.2
  auto_size_text: ^3.0.0

  flutter_blurhash: 0.8.2



  device_info_plus: ^9.0.2
  saver_gallery: ^4.0.0
  share_plus: ^10.1.2
  file_picker: ^8.1.4



  flutter_html: ^3.0.0-beta.2
  flutter_bbcode: ^1.5.0
  timezone: ^0.9.4
  font_awesome_flutter: ^10.1.0
  flutter_rating_bar: ^4.0.1
  intl: ^0.19.0
  animations: ^2.0.3
  vector_math: any



dev_dependencies:
  flutter_native_splash: ^2.3.9
  flutter_launcher_icons: "^0.13.1"
  flutter_test:
    sdk: flutter

#dependency_overrides:  ###possible fix for nested inappwebview text selection.
  #webview_flutter:
    #git:
      #url: https://github.com/Blazesmoker/plugins.git
      #path: packages/webview_flutter/webview_flutter
      #ref: main

flutter_icons:
  android: false
  ios: true
  image_path: "assets/icons/AppIcon.png"


flutter_native_splash:
  color: "#000000"
  image: assets/icons/fathemed.png #assets/icons/fathemed.png
  android: true
  ios: false
  fullscreen: true
  android_gravity: center






flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/images/defaultpic.gif
    - assets/emojis/
    - packages/timezone/data/latest_all.tzf
  fonts:

    - family: WorkSans
      fonts:
        - asset: assets/fonts/WorkSans-Regular.ttf
        - asset: assets/fonts/WorkSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/WorkSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/WorkSans-Bold.ttf
          weight: 700
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 400
